config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  get '/posts/new', to: 'posts#new', as: 'create_post'
  post '/posts/new', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'post'
  post '/users/:user_id/posts/:id/', to: 'posts#create_comment'
  post '/users/:user_id/posts/:id/likes', to: 'posts#create_like', as: 'like'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
end

app/models/application_record.rb
# rubocop:disable all
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# rubocop:disable all
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post', foreign_key: :post_id
  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
# rubocop:disable all
# rubocop:disable all
class Like < ApplicationRecord
   belongs_to :author, class_name: 'User', foreign_key: :author_id
   belongs_to :post, class_name: 'Post', foreign_key: :post_id
   after_save :update_like_counter

  private

  def update_like_counter
    post.increment!(:likes_counter)
  end

end

app/models/post.rb
# rubocop:disable all
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250, too_long: '250 characters in post is the maximum allowed.' }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
# rubocop:disable all
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
# rubocop:disable all
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    post = Post.find(params[:post_id])
    comment = Comment.create(author: current_user, post: comment_params)
    return unless comment.save

    redirect_to user_post_path(current_user.id, post.id), notice: 'Comment saved'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
# rubocop:disable all
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]
    if @like.save!
      redirect_to user_posts_path(current_user)
    else
      redirect_to :new
    end
  end
end

app/controllers/posts_controller.rb
# rubocop:disable all
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comment = Comment.new
    @like = Like.new
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:id])
    @comment.author = current_user
    redirect_to post_path if @comment.save
  end

  def create_like
    @like = Like.new(author: current_user, post: Post.find(params[:id]))
    redirect_to post_path if @like.save
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0
    return unless @post.save

    redirect_to posts_new_path
    flash[:success] = 'Post have been saved successfully'
  end

  def new
    @post = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/users_controller.rb
# rubocop:disable all
class UsersController < ApplicationController
  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# rubocop:disable all
module ApplicationHelper
end

app/helpers/comments_helper.rb
# rubocop:disable all
module CommentsHelper
end

app/helpers/likes_helper.rb
# rubocop:disable all
module LikesHelper
end

app/helpers/posts_helper.rb
# rubocop:disable all
module PostsHelper
end

app/helpers/users_helper.rb
# rubocop:disable all
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>BlogAppWithRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <div><%= yield %></div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Post</h1>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :comments_counter, style: "display: block" %>
    <%= form.number_field :comments_counter %>
  </div>

  <div>
    <%= form.label :likes_counter, style: "display: block" %>
    <%= form.number_field :likes_counter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='post-item'>
    <h3>Post #<%= post.id %>
        <%= link_to post.title,user_post_path(@user, post) %>
    </h3>
    <p><%= post.text%></p>
    <div class='post-details'>
        <p>Comments: <%= post.comments.size %></p>
        <p>Likes: <%= post.likes.size%></p>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<section class='user-posts'>
    <nav>
        <%= render 'users/user', user: @user %>
    </nav>
    <% @user.recent_posts.each_with_index do |post, id| %>
        <div class='post-user'>
            <%= render 'posts/post', post: post %>
            <div class='user-comments'>
                <% post.recent_comments.each do |comment| %>
                    <p>
                        <strong>
                            <%= comment.author.name %>
                        </strong>
                        :<%= comment.text %>
                    </p>
                <% end %>
            </div>
        </div>
    <% end %>
</section>

app/views/posts/new.html.erb
<div class="post-container">
  <h1>Create New Post</h1>

  <%= form_with model: @post, url: posts_new_path, method: :post, scope: :post do |f| %>
    <div class="column">
      <%= f.text_field :title, placeholder: 'Title of post', class: 'text-input' %>
      <%= f.text_area :text,placeholder: 'Description of post' %>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="my-comment">
  <div class="comment-bio">
      <div class='comment-header'>
        <p class='title'><%= @post.title %> by <%= @user.name %></p>
        <div class='comment-details'>
            <p>Comments: <%= @post.comments.size %></p>
            <p>Likes: <%= @post.likes.size %></p>
        </div>
      </div>
      <p class="comment-text"><%= @post.text%></p>
  </div>
  <div class="comments">
      <div class="comment-item">
        <% @post.comments.each do |comment|%>
            <p><%= comment.author.name %> <%= comment.text %></p>
        <% end %>
      </div>
  </div>
  <div class='post-feature'>
    <%= form_with model: @like, url: like_path, method: :post do |f| %>
        <%= f.submit "Like post", class: "like-post" %>
    <% end %>
    <%= form_with model: @comment, url: post_path, method: :post, scope: :comment do |f| %>
      <div class="comment-section">
        <%= f.text_area :text, placeholder: "Add Comment", class: "comment" %>
        <%= f.submit "Comment", class: "submit-comment" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio %>
  </div>

  <div>
    <%= form.label :posts_counter, style: "display: block" %>
    <%= form.number_field :posts_counter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class='user-item'>
    <img src="<%= user.photo %>" alt='avatar-<%= user.name%>' class='user-avatar'><br>
    <div class='user-description'>
        <h2 class='user-name'>
            <%= link_to user.name , user %>
        </h2>
        <span class='post-number'>Post counter: <%= user.posts_counter == nil ? 0 : user.posts_counter %></span>
    </div>
</div>

app/views/users/edit.html.erb

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<section class='users-list'>
  <% @users.each do |user| %>
    <%= render "users/user", user: user %>
  <% end %>

  <div>
    <%= link_to create_post_path do %>
      <button class="create-post">create post</button>
    <%end%>
  </div>
</section>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>

app/views/users/show.html.erb
<section class='user-details'>
    <nav>
        <%= render "users/user", user: @user %>
    </nav>
    <div class='bio'>
        <h3>Bio</h3>
        <p><%= @user.bio%></p>
    </div>
    <% @user.recent_posts.each do |post| %>
        <%= render 'posts/post', post: post %>
    <% end %>
    <button type="button" class="see-all-posts">
        <%= link_to "See All Posts", user_posts_path(@user) %>
    </button>
</section>